version: "3.4"

services:
  web:
    image: ${DOCKER_REGISTRY-}pwrsyllabus
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "51929:5000"
      - "51930:5001"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    hostname: "sqlserver"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    ports:
      - "1433:1433"
    expose:
      - 1433